# Generated by Django 3.2.6 on 2021-08-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20210814_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiondetail',
            name='browser',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sessiondetail',
            name='browser_version',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sessiondetail',
            name='device_brand',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sessiondetail',
            name='device_family',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sessiondetail',
            name='device_model',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sessiondetail',
            name='os',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sessiondetail',
            name='os_version',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sessiondetail',
            name='remote_ip',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sessiondetail',
            name='remote_ip_country',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sessiondetail',
            name='token',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sessiondetail',
            name='user_agent',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
