# Generated by Django 3.2.6 on 2021-08-17 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20210817_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessiondetail',
            name='device_brand',
        ),
        migrations.RemoveField(
            model_name='sessiondetail',
            name='device_model',
        ),
        migrations.RemoveField(
            model_name='sessiondetail',
            name='token',
        ),
    ]
