# Generated by Django 3.2.6 on 2021-08-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20210817_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiondetail',
            name='token',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
