# Generated by Django 3.2.6 on 2021-08-11 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_user', '0001_initial'),
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='account',
        ),
        migrations.AddField(
            model_name='group',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App_user.app_user'),
        ),
    ]
