# Generated by Django 3.2.6 on 2021-08-11 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20210811_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='page',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='page',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
