# Generated by Django 3.2.6 on 2021-08-11 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_group_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='account',
        ),
    ]
