# Generated by Django 3.2.6 on 2021-08-13 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_account'),
        ('cms', '0005_remove_group_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.account'),
        ),
    ]
