# Generated by Django 3.2.6 on 2021-08-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_remove_group_account'),
        ('App_user', '0002_auto_20210812_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='groups',
            field=models.ManyToManyField(to='cms.Group'),
        ),
    ]
