# Generated by Django 3.2.6 on 2021-08-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_user', '0004_auto_20210812_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='password1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='password2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
