# Generated by Django 3.2.6 on 2021-08-13 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_account'),
        ('App_user', '0006_alter_appuser_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.account'),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
