# Generated by Django 3.2.6 on 2021-08-13 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_user', '0008_auto_20210814_0130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='password1',
            new_name='confirm_password',
        ),
        migrations.RenameField(
            model_name='appuser',
            old_name='password2',
            new_name='password',
        ),
    ]
