# Generated by Django 3.2.6 on 2021-08-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_user', '0009_auto_20210814_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
